#!/bin/bash


# make this an option
# java tools/GenerateAst.java tool/
# java tools/GenerateAst.java src/

# javac com/craftinginterpreters/lox/[^AstPrinter]*.java && jar -cfm lox.jar manifest.txt com/

javac com/craftinginterpreters/lox/*.java && jar -cfm lox.jar manifest.txt com/

# This works with the args file and makes a jar
# javac @args && jar -cfm lox.jar manifest.txt com/